[package]
name = "transmitter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bitvec = "1.0.1"
clap = { version = "4.5.30", features = ["derive"] }
hound = "3.5.1"
libhackrf = "0.1.1"
